# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build windows.amd64
      run: env GOOS=windows GOARCH=amd64 go build -o christmasTree.windows.amd64 -ldflags="-s" ./christmasTree.go

    - name: Build linux.amd64
      run: env GOOS=linux GOARCH=amd64 go build -o christmasTree.linux.amd64 -ldflags="-s" ./christmasTree.go
      
    - name: Build darwin.amd64
      run: env GOOS=darwin GOARCH=amd64 go build -o christmasTree.darwin.amd64 -ldflags="-s" ./christmasTree.go
 
    - name: Build darwin.arm64
      run: env GOOS=darwin GOARCH=arm64 go build -o christmasTree.darwin.arm64 -ldflags="-s" ./christmasTree.go

